<?php

    return [
        [
            "title" => "Regal Beach Club",
            "image" => "img/regal-beach-club.jpg",
            "location" => "Appartamento",
            "stars" => 5,
            "address" => "George Town",
            "vote" => 9,
            "free_cancellation" => 1,
            "room" => "Appartamento Vista Mare",
            "board" => "Mezza Pensione",
            "price" => "€ 1.966",
        ],
        [
            "title" => "Holiday Inn Resort Aruba",
            "image" => "img/holiday-inn-resort-aruba.jpeg",
            "location" => "Residence",
            "stars" => 5,
            "address" => "Palm-Eagle Beach",
            "vote" => 8.5,
            "free_cancellation" => 0,
            "room" => "Camera Standard matrimoniale/doppia con Letti Singoli",
            "board" => "Pensione Completa",
            "price" => "€ 1.318",
        ],
        [
            "title" => "Green Castle Eco Hotel",
            "image" => "img/green-castle-eco-hotel.jpg",
            "location" => "Residence",
            "stars" => 4,
            "address" => "Mount Pleasant",
            "vote" => 8,
            "free_cancellation" => 1,
            "room" => "Camera Standard doppia con Letti Singoli e Vista Giardino",
            "board" => "Mezza Pensione",
            "price" => "€ 552",
        ],
        [
            "title" => "Villa des îles",
            "image" => "img/villa-des-iles.jpg",
            "location" => "Appartamento",
            "stars" => 3,
            "address" => "Basse-Terre",
            "vote" => 9,
            "free_cancellation" => 0,
            "room" => "Appartamento con Vista Giardino",
            "board" => "Pensione Completa",
            "price" => "€ 314",
        ],
        [
            "title" => "Las Terrazas VIP Pool Beach Club & Spa",
            "image" => "img/las-terrazas-vip-beach-club.jpg",
            "location" => "Resort",
            "stars" => 4,
            "address" => "Bavaro, Punta Cana",
            "vote" => 8.5,
            "free_cancellation" => 1,
            "room" => "Condo Deluxe con Accesso Stabilimento Balneare",
            "board" => "Mezza Pensione",
            "price" => "€ 697",
        ]
    ];

?>